# permissions to do edit jobruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jobrun-editor-role
rules:
- apiGroups:
  - batch.joboperator.io
  resources:
  - jobruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.joboperator.io
  resources:
  - jobruns/status
  verbs:
  - get
  - patch
  - update
