# permissions to do viewer jobruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jobrun-viewer-role
rules:
- apiGroups:
  - batch.joboperator.io
  resources:
  - jobruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.joboperator.io
  resources:
  - jobruns/status
  verbs:
  - get
