
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch.joboperator.io
  resources:
  - jobruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.joboperator.io
  resources:
  - jobruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch.joboperator.io
  resources:
  - jobtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.joboperator.io
  resources:
  - jobtemplates/status
  verbs:
  - get
  - patch
  - update
